//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MapGeneratorGUITest extends JPanel {
    private JButton jcomp1;
    private JButton jcomp2;
    private JSlider jcomp3;
    private JSlider jcomp4;
    private JCheckBox jcomp5;
    private JCheckBox jcomp6;
    private JTextArea jcomp7;
    private JLabel jcomp8;
    private JLabel jcomp9;

    public MapGeneratorGUITest() {
        //construct components
        jcomp1 = new JButton ("Generate Map");
        jcomp2 = new JButton ("Save Input");
        jcomp3 = new JSlider (0, 5);
        jcomp4 = new JSlider (0, 10);
        jcomp5 = new JCheckBox ("Spawn Enemies?");
        jcomp6 = new JCheckBox ("Spawn Treasure?");
        jcomp7 = new JTextArea (5, 5);
        jcomp8 = new JLabel ("Number of Tiles");
        jcomp9 = new JLabel ("Zoom Level");

        //set components properties
        jcomp3.setOrientation (JSlider.HORIZONTAL);
        jcomp3.setMinorTickSpacing (1);
        jcomp3.setMajorTickSpacing (5);
        jcomp3.setPaintTicks (true);
        jcomp3.setPaintLabels (true);
        jcomp4.setOrientation (JSlider.HORIZONTAL);
        jcomp4.setMinorTickSpacing (1);
        jcomp4.setMajorTickSpacing (5);
        jcomp4.setPaintTicks (true);
        jcomp4.setPaintLabels (true);

        //adjust size and set layout
        setPreferredSize (new Dimension (944, 601));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (jcomp4);
        add (jcomp5);
        add (jcomp6);
        add (jcomp7);
        add (jcomp8);
        add (jcomp9);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (640, 475, 275, 95);
        jcomp2.setBounds (80, 500, 170, 50);
        jcomp3.setBounds (25, 150, 270, 55);
        jcomp4.setBounds (25, 55, 270, 55);
        jcomp5.setBounds (90, 275, 130, 25);
        jcomp6.setBounds (90, 230, 135, 25);
        jcomp7.setBounds (25, 340, 280, 135);
        jcomp8.setBounds (30, 120, 100, 25);
        jcomp9.setBounds (30, 25, 100, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("MapGeneratorGUITest");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new MapGeneratorGUITest());
        frame.pack();
        frame.setVisible (true);
    }
}
